apiVersion: v1
kind: Service
metadata:
  name: taskflow-api
  labels:
    app: taskflow-api
spec:
  selector:
    app: taskflow-api
  ports:
    # TODO (lab01): exponer el puerto donde escucha Kestrel dentro del pod.
    - name: http
      port: 8080
      targetPort: TODO
