apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  labels:
    app: taskflow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: taskflow-api
          # SOLUCIÓN (lab03): imagen productiva publicada en este lab.
          image: "image-registry.openshift-image-registry.svc:5000/tu-namespace/taskflow-api:lab03"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: taskflow-config
          env:
            - name: Db__Username
              valueFrom:
                secretKeyRef:
                  name: taskflow-db-credentials
                  key: username
            - name: Db__Password
              valueFrom:
                secretKeyRef:
                  name: taskflow-db-credentials
                  key: password
          securityContext:
            readOnlyRootFilesystem: true
            # SOLUCIÓN (lab03): hardening completo.
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            # SOLUCIÓN (lab03): valores livianos acordes a un lab.
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
